### PR TITLE
A number of improvements

### PR DESCRIPTION
**Pull request by lichray**
Building:
  - CMake with out-of-source build support.

Testing:
  - C++11 random utilities.  Now you can control the
    range of the generated random floating point
    numbers with --lower=16 --upper=3e16, for example.

Performance (mainly focusing on Errol4):
  - Fast digits generation.
  - Replace floating point routines with integer/bits
    operations when possible.
  - Use divmod when compiler does not.

Binary size:
 - Replace the 4x1024 hash tables with lists
    without losing performance by arranging
    the elements in binary search tree's level
    order.  Our library is now strictly smaller
    than double-conversion (even though we
    packed 5 algorithms).

Benchmark:
Ubuntu 16.04.1 LTS
```
model name      : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpu cores       : 1
```
```
$ gcc -v
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

$ ./test/run --perf=5K --lower=1.80143985094820e16 --upper=3.40282366920937e38
==== Absolute Results ====
Errol0            2241 cycles
Errol1            836 cycles
Errol2            887 cycles
Errol3            620 cycles
Errol4            613 cycles
Grisu3            433 cycles
Dragon4           2347 cycles
Grisu3 w/fallback 463 cycles
==== Relative Speedup of Errol3 ====
Grisu3            0.70x
Dragon4           3.78x
Grisu3 w/fallback 0.75x
==== Relative Speedup of Errol4 ====
Grisu3            0.71x
Dragon4           3.82x
Grisu3 w/fallback 0.75x

$ ./test/run --perf=5K
==== Absolute Results ====
Errol0            6439 cycles
Errol1            879 cycles
Errol2            894 cycles
Errol3            824 cycles
Errol4            339 cycles
Grisu3            470 cycles
Dragon4           4766 cycles
Grisu3 w/fallback 493 cycles
==== Relative Speedup of Errol3 ====
Grisu3            0.57x
Dragon4           5.78x
Grisu3 w/fallback 0.60x
==== Relative Speedup of Errol4 ====
Grisu3            1.38x
Dragon4           14.02x
Grisu3 w/fallback 1.45x

```
```
$ clang -v
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

$ ./test/run --perf=5K --lower=1.80143985094820e16 --upper=3.40282366920937e38
==== Absolute Results ====
Errol0            2372 cycles
Errol1            1045 cycles
Errol2            811 cycles
Errol3            596 cycles
Errol4            602 cycles
Grisu3            412 cycles
Dragon4           2490 cycles
Grisu3 w/fallback 444 cycles
==== Relative Speedup of Errol3 ====
Grisu3            0.69x
Dragon4           4.18x
Grisu3 w/fallback 0.74x
==== Relative Speedup of Errol4 ====
Grisu3            0.68x
Dragon4           4.13x
Grisu3 w/fallback 0.74x

$ ./test/run --perf=5K
==== Absolute Results ====
Errol0            6724 cycles
Errol1            1088 cycles
Errol2            1059 cycles
Errol3            1042 cycles
Errol4            420 cycles
Grisu3            469 cycles
Dragon4           4921 cycles
Grisu3 w/fallback 497 cycles
==== Relative Speedup of Errol3 ====
Grisu3            0.45x
Dragon4           4.72x
Grisu3 w/fallback 0.48x
==== Relative Speedup of Errol4 ====
Grisu3            1.12x
Dragon4           11.70x
Grisu3 w/fallback 1.18x

```
FreeBSD 11.0-RELEASE-p2
```
hw.model: Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
hw.ncpu: 1
```
```
% clang -v
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)

% ./test/run --perf=5K --lower=1.80143985094820e16 --upper=3.40282366920937e38
==== Absolute Results ====
Errol0            2501 cycles
Errol1            1164 cycles
Errol2            1468 cycles
Errol3            1445 cycles
Errol4            1436 cycles
Grisu3            563 cycles
Dragon4           2976 cycles
Grisu3 w/fallback 598 cycles
==== Relative Speedup of Errol3 ====
Grisu3            0.39x
Dragon4           2.06x
Grisu3 w/fallback 0.41x
==== Relative Speedup of Errol4 ====
Grisu3            0.39x
Dragon4           2.07x
Grisu3 w/fallback 0.42x

% ./test/run --perf=5k
==== Absolute Results ====
Errol0            7387 cycles
Errol1            1340 cycles
Errol2            1317 cycles
Errol3            1157 cycles
Errol4            551 cycles
Grisu3            591 cycles
Dragon4           5819 cycles
Grisu3 w/fallback 615 cycles
==== Relative Speedup of Errol3 ====
Grisu3            0.51x
Dragon4           5.03x
Grisu3 w/fallback 0.53x
==== Relative Speedup of Errol4 ====
Grisu3            1.07x
Dragon4           10.55x
Grisu3 w/fallback 1.12x

```

\* All tests are done by ensuring that the same compiler is being used to build both `libdouble-conversion.a` and `liberrol.a`.
\*\* On FreeBSD 11 other compilers perform roughly the same comparing to the stock Clang, very likely because of that `compiler-rt` is not as optimized as `libgcc`.

So overall we beat `double-conversion` by 10%-40%, in the worst ranges we archive 40%-70% performance comparing to `double-conversion`, in the best ranges we archive up to 2x (from 16 to 3e16, not shown above).

### CODE REVIEW

**Review by marcandrysco — CHANGES_REQUESTED** [review]
I had to make a couple tweaks to get it to build by default on my machine using make (not cmake), included the diff below.

Otherwise, really good job with improving the algorithm! I believe this will be a welcome sight for some language implementors.

diff --git a/test/Makefile b/test/Makefile
index 09c66bd..c06d87f 100644
--- a/test/Makefile
+++ b/test/Makefile
@@ -2,8 +2,8 @@
 
 CC      = gcc
 CXX     = g++
-LD      = gcc
-CFLAGS  = -g -O2 -Wall -Werror
+LD      = g++
+CFLAGS  = -g -O2 -Wall -Werror -I../lib -I../grisu/src
 LDFLAGS = -lm -L../lib -L../grisu -static -lerrol -ldouble-conversion -lm -lgmp
 AR      = ar rcs
 
diff --git a/test/interop.cpp b/test/interop.cpp
index 4296ec1..2467d4c 100644
--- a/test/interop.cpp
+++ b/test/interop.cpp
@@ -1,4 +1,4 @@
-#include <double-conversion/fast-dtoa.h>
+#include <fast-dtoa.h>
 #include <errol.h>

**Comment by lichray** [comment]
I analyzed your workflow, then locally patched `double-conversion`'s `SConstruct` & your `Makefile` to place the headers and the library to the paths that are relatively compatible with my workflow.  Give it a try.

**Review by marcandrysco — CHANGES_REQUESTED** [review]
The include directly wasn't quite lining up so I made a pair of changes:

diff --git a/grisu/SConstruct b/grisu/SConstruct
index 3bcd219..8512226 100644
--- a/grisu/SConstruct
+++ b/grisu/SConstruct
@@ -17,7 +17,7 @@ DESTDIR = ARGUMENTS.get('DESTDIR', '')
 prefix = ARGUMENTS.get('prefix', '/usr/local')
 lib = ARGUMENTS.get('libsuffix', 'lib')
 libdir = os.path.join(DESTDIR + prefix, lib)
-incdir = os.path.join(DESTDIR + prefix, 'include')
+incdir = os.path.join(DESTDIR + prefix, 'double-conversion')
 
 env = Environment(CPPPATH='#/src', LIBS=['m', 'stdc++'],
     CXXFLAGS=ARGUMENTS.get('CXXFLAGS', ''))
diff --git a/test/Makefile b/test/Makefile
index 49d62fa..f941d38 100644
--- a/test/Makefile
+++ b/test/Makefile
@@ -4,7 +4,7 @@ CC      = gcc
 CXX     = g++
 LD      = g++
 CFLAGS  = -g -O2 -Wall -Werror -I../lib
-CXXFLAGS= -g -O2 -std=c++11 -Wall -Werror -I../lib -I../grisu/include
+CXXFLAGS= -g -O2 -std=c++11 -Wall -Werror -I../lib -I../grisu
 LDFLAGS = -L../lib -L../grisu/lib -static -lerrol -ldouble-conversion -lm -lgmp
 AR      = ar rcs

**Comment by lichray** [comment]
Oops.  Fixed (forced update, please reset your local branch).

**Comment by marcandrysco** [comment]
Changes merged and everything is working well. Awesome!

**Pull request merged**
